# Generated by Django 2.2 on 2020-12-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
